server:
  port: 8083

spring:
  application:
    name: order-service
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

clients:
  customer-service:
    url: http://localhost:8081
  catalog-service:
    url: http://localhost:8082